name: build

on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - .github/workflows/build.yml
      - dockerfile
      - build.sh
      - fvp.sh
      - fvprc

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install Ubuntu deps
        run: |
          sudo apt-get update
          sudo apt-get install \
            shellcheck

      - uses: ammaraskar/gcc-problem-matcher@0f9c86f9e693db67dacf53986e1674de5f2e5f28 # master

      - name: Run ShellCheck
        run: |
          shellcheck -s bash -f gcc *.sh fvprc

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: dockerfile

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit
            
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Create .armlm
        run: mkdir -p ~/.armlm

      - name: Build Docker image
        run: ./build.sh

      - name: Run FVP binaries to verify build
        run: | 
          for x in ./bin/*; do
            echo "$x --version"
            $x --version || exit 1
          done
